inventory:
  plugin: SimpleInventory
  options:
    host_file: "./hosts.yaml"
    group_file: "./groups.yaml"
    defaults_file: "~/nornir_inventory/defaults.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 20
