---
cisco3:
    hostname: cisco3.lasthop.io
    groups:
      - ios
    data:
      interfaces:
        loopback123:
          state: no shut
          descr: ntp source loopback
        loopback10:
          state: no shut
          descr: primary loopback

cisco4:
    hostname: cisco4.lasthop.io
    groups:
      - ios
    data:
      interfaces:
        loopback93:
          state: shut
          descr: legacy; delete

nxos1:
    hostname: nxos1.lasthop.io
    groups:
      - nxos

nxos2:
    hostname: nxos2.lasthop.io
    groups:
      - nxos

arista1:
    hostname: arista1.lasthop.io
    groups:
      - eos

arista2:
    hostname: arista2.lasthop.io
    groups:
      - eos

arista3:
    hostname: arista3.lasthop.io
    groups:
      - eos

arista4:
    hostname: arista4.lasthop.io
    groups:
      - eos

srx2:
    hostname: srx2.lasthop.io
    groups:
      - junos
